//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EzProcess.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EzProcess.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be null.
        /// </summary>
        internal static string CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting role id in parameter and model data..
        /// </summary>
        internal static string CONFLICT_ROLE_ID_PARAM {
            get {
                return ResourceManager.GetString("CONFLICT_ROLE_ID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required when changing your own..
        /// </summary>
        internal static string CURRENT_PASSWORD_IS_REQUIRED {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not deactive last administrator account..
        /// </summary>
        internal static string ERR_CANNOT_DEACTIVE_LAST_ADMIN {
            get {
                return ResourceManager.GetString("ERR_CANNOT_DEACTIVE_LAST_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete last administrator account..
        /// </summary>
        internal static string ERR_CANNOT_DELETE_LAST_ADMIN {
            get {
                return ResourceManager.GetString("ERR_CANNOT_DELETE_LAST_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your permission can not edit administrator account.
        /// </summary>
        internal static string ERR_CANNOT_EDIT_ADMIN_ACCOUNT {
            get {
                return ResourceManager.GetString("ERR_CANNOT_EDIT_ADMIN_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred whilst creating:.
        /// </summary>
        internal static string ERR_WHEN_CREATE {
            get {
                return ResourceManager.GetString("ERR_WHEN_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred whilst deleting:.
        /// </summary>
        internal static string ERR_WHEN_DELETE {
            get {
                return ResourceManager.GetString("ERR_WHEN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred whilst deleting role: .
        /// </summary>
        internal static string ERR_WHEN_DELETE_ROLE {
            get {
                return ResourceManager.GetString("ERR_WHEN_DELETE_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred whilst deleting user: .
        /// </summary>
        internal static string ERR_WHEN_DELETE_USER {
            get {
                return ResourceManager.GetString("ERR_WHEN_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred whilst unblocking user: .
        /// </summary>
        internal static string ERR_WHEN_UNBLOCK_USER {
            get {
                return ResourceManager.GetString("ERR_WHEN_UNBLOCK_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred whilst updating:.
        /// </summary>
        internal static string ERR_WHEN_UPDATE {
            get {
                return ResourceManager.GetString("ERR_WHEN_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following errors occurred whilst updating User Configurations: .
        /// </summary>
        internal static string ERR_WHEN_UPDATE_USER_PREF {
            get {
                return ResourceManager.GetString("ERR_WHEN_UPDATE_USER_PREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be deleted. Remove all users from this role and try again..
        /// </summary>
        internal static string ROLE_CAN_NOT_BE_DELETE {
            get {
                return ResourceManager.GetString("ROLE_CAN_NOT_BE_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username/password couple is invalid..
        /// </summary>
        internal static string USERNAME_AND_PASSWORD_COUPLE_INVALID {
            get {
                return ResourceManager.GetString("USERNAME_AND_PASSWORD_COUPLE_INVALID", resourceCulture);
            }
        }
    }
}
